name: mostruario.online deployment
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
phpunit:
  runs-on: ubuntu-latest
  steps:
    - name: Install PHP 8.2
      run: |
        sudo add-apt-repository ppa:ondrej/php
        sudo apt-get update
        sudo apt-get install php8.2 -y
    - name: Check PHP version
      run: php8.2 --version
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
    - name: Get yarn cache
      id: yarn-cache
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - uses: actions/cache@v1
      with:
        path: ${{ steps.yarn-cache.outputs.dir }}
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - name: Install composer dependencies
      run: |
        composer install --no-scripts
    - name: Prepare Laravel Application
      run: |
        cp .env.ci .env
        php artisan key:generate
    - name: Install front-end dependencies
      run: |
        npm install
        npm run dev
    - name: Run Testsuite
      run: vendor/bin/phpunit tests/
        
  deploy-production:
      runs-on: ubuntu-latest 
      environment:
        name: production
        url: ${{ vars.URL }}
      needs: phpunit 
      steps:
        - name: Repo Checkout
          uses: actions/checkout@v1
        - name: Hostinger Deployment
          uses: easingthemes/ssh-deploy@main
          with: 
            SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
            ARGS: "-rlgoDzvc --delete"
            SOURCE: "/"
            REMOTE_HOST: ${{ vars.REMOTE_HOST }}
            REMOTE_USER: ${{ vars.REMOTE_USER }}
            REMOTE_PORT: ${{ vars.REMOTE_PORT }}
            TARGET: ${{ vars.TARGET }}
        
