name: mostruario.online deployment
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kirschbaumdevelopment/laravel-test-runner:8.1      
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ vars.PASSWORD }}
          MYSQL_DATABASE: u681759714_mostruario
        ports:
          - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Check PHP version
        run: php --version
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Get Composer Cache Directory
        id: composer-cache
        run: |
          echo "::set-output name=dir::$(composer config cache-files-dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install composer dependencies
        run: |
          curl -O https://getcomposer.org/installer
          php installer
          rm -rf installer
          php composer.phar install
      - name: Prepare Laravel Application
        run: |
          cp .env.ci .env
          php artisan key:generate
    #  - name: Install front-end dependencies
    #    run: |
    #      npm install
    #      npm run dev
    #  - name: Run PHPUnit Tests
    #    run: vendor/bin/phpunit
        
  deploy-production:
      runs-on: ubuntu-latest 
      environment:
        name: production
        url: ${{ vars.URL }}
      needs: build 
      steps:
        - name: Repo Checkout
          uses: actions/checkout@v1
        - name: Hostinger Deployment
          uses: easingthemes/ssh-deploy@main
          with: 
            SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
            ARGS: "-rlgoDzvc --delete"
            SOURCE: "/"
            REMOTE_HOST: ${{ vars.REMOTE_HOST }}
            REMOTE_USER: ${{ vars.REMOTE_USER }}
            REMOTE_PORT: ${{ vars.REMOTE_PORT }}
            TARGET: ${{ vars.TARGET }}
        
