name: mostruario.online deployment

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  composer:
    runs-on: ubuntu-latest
    container:
      image: lorisleiva/laravel-docker:latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Instalar dependências do Composer
        run: |
          composer install --prefer-dist --no-ansi --no-interaction --no-progress --no-scripts
          cp .env.ci .env
          php artisan key:generate

      - name: Armazenar cache do Composer
        uses: actions/cache@v2
        with:
          path: vendor/
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-

      - name: Salvar artefatos
        uses: actions/upload-artifact@v2
        with:
          name: composer
          path: vendor/

  npm:
    runs-on: ubuntu-latest
    container:
      image: lorisleiva/laravel-docker:latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2
  
      - name: Instalar dependências do NPM
        run: |
          npm install
          npm run production
  
      - name: Armazenar cache do NPM
        uses: actions/cache@v2
        with:
          path: node_modules/
          key: ${{ runner.os }}-npm-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
  
      - name: Salvar artefatos
        uses: actions/upload-artifact@v2
        with:
          name: npm
          path: 
            node_modules/
            public/css/
            public/js/

  #phpunit:
  #  runs-on: ubuntu-latest
  #  container:
  #    image: lorisleiva/laravel-docker:latest
  #  steps:
  #    - name: Checkout do código
  #      uses: actions/checkout@v2

  #    - name: Instalar PHPUnit
  #      run: composer require --dev phpunit/phpunit

  #    - name: Rodar PHPUnit
  #      run: phpunit --coverage-text --colors=never

  deploy-production:
    runs-on: ubuntu-latest 
    container:
      image: lorisleiva/laravel-docker:latest
    environment:
      name: production
      url: ${{ vars.URL }}
    needs:
      - composer
      - npm
    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Inicializar SSH
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.SERVER_SSH_KEY }}" | tr -d '\r' | ssh-add - > /dev/null
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

      - name: Alterar permissões de arquivos
        run: |
          find . -type f -not -path "./vendor/*" -exec chmod 664 {} \;
          find . -type d -not -path "./vendor/*" -exec chmod 775 {} \;

      - name: Hostinger Deployment
        uses: easingthemes/ssh-deploy@main
      
        with: 
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rlgoDzvc --delete"
          SOURCE: "/"
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          REMOTE_PORT: ${{ vars.REMOTE_PORT }}
          TARGET: ${{ vars.TARGET }}
