name: mostruario.online deployment

on: 
  push:
    branches: [main]

jobs:
  deploy-stage:
    runs-on: ubuntu-latest
    environment:
      name: stage
      url: ${{ vars.URL }}
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Hostinger Deployment
        uses: easingthemes/ssh-deploy@main
        with: 
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rlgoDzvc"
          SOURCE: "/"
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          REMOTE_PORT: ${{ vars.REMOTE_PORT }}
          TARGET: ${{ vars.TARGET }}

  run-tests:
    runs-on: ubuntu-latest
    needs: deploy-stage
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurando ambiente de teste
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.REMOTE_HOST }}
          username: ${{ vars.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ vars.REMOTE_PORT }}
          script_stop: true
          script: |
            cd domains/mostruario.online/public_html/teste_stage
            composer2 install --no-dev --no-interaction --no-progress --prefer-dist
            rm -rf node_modules/
            npm install --y
            npm run build
            php artisan optimize
            composer2 update
            php artisan migrate --force
            php artisan up 
            php artisan migrate --force

      - name: Rodando os testes
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.REMOTE_HOST }}
          username: ${{ vars.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ vars.REMOTE_PORT }}
          script: |
            cd domains/mostruario.online/public_html/teste_stage
            php artisan test --stop-on-failure

      - name: Configurando ambiente de producao
        if: always()
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ vars.REMOTE_HOST }}
          username: ${{ vars.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ vars.REMOTE_PORT }}
          script_stop: true
          script: |
            cd domains/mostruario.online/public_html
            cp .env.production .env

  deploy-production:
    runs-on: ubuntu-latest
    needs: run-tests
    environment:
      name: production
      url: ${{ vars.URL }}
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Hostinger Deployment
        uses: easingthemes/ssh-deploy@main
        with: 
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rlgoDzvc"
          SOURCE: "/"
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          REMOTE_PORT: ${{ vars.REMOTE_PORT }}
          TARGET: ${{ vars.TARGET }}
          SCRIPT_AFTER: |
            cd domains/mostruario.online/public_html
            composer2 install --no-dev --no-interaction --no-progress --prefer-dist
            rm -rf node_modules/
            npm install --y
            npm run build
            php artisan optimize
            composer2 update
            php artisan migrate --force
            php artisan up 