name: mostruario.online deployment

on: 
  push:
    branches: [master]

jobs:
  deploy-production:

    runs-on: ubuntu-latest 
    
    environment:
      name: production
      url: ${{ vars.URL }}
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Hostinger Deployment
        uses: easingthemes/ssh-deploy@main
      
        with: 
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-rlgoDzvc"
          SOURCE: "/"
          REMOTE_HOST: ${{ vars.REMOTE_HOST }}
          REMOTE_USER: ${{ vars.REMOTE_USER }}
          REMOTE_PORT: ${{ vars.REMOTE_PORT }}
          TARGET: ${{ vars.TARGET }}
          SCRIPT_AFTER: |
            cd domains/mostruario.online/public_html
            
            # Instala as dependências PHP
            composer2 install --no-dev --no-interaction --no-progress --prefer-dist

            # Instala as dependências JS
            rm -rf node_modules/
            
            npm install --y

            npm run build

            # Atualiza o cache da aplicação
            php artisan optimize

            # Atualiza as dependências
            composer2 update

            # Realiza as migrações
            php artisan migrate --force

            # Finalzia as atualizações
            php artisan up 